### ISSUE TITLE
cannot close tags on Sublime Text 3

### ISSUE THREAD

**Issue by cfjesse** [SublimeText/ColdFusion#154] opened 2015-01-19 16:14 UTC
I really like this plugin and I use it on Sublime Text 2 all the time.  But on Sublime Text 3 when I start for example a `<cfset` tag or any other tag it won't allow me to type the close for the tag `>` I am on windows 7 PC.  I am a Coldfusion and javascript developer. This issue is one of the reasons why I have not completely upgraded to ST3.

**Comment by atuttle** [comment] 2015-01-19 16:35
Closing as a duplicate of #106

**Closed by atuttle** 2015-01-19 16:35 UTC

**Comment by deltaforce** [comment] 2017-09-22 20:22
crikey 1 year and 8 months later, and this bug still exists.
The plugin is not really usable at all if you cannot close tags.

**Comment by atomi** [comment] 2017-09-22 21:00
try https://github.com/jcberquist/sublimetext-cfml

**Comment by jevans-gp** [comment] 2017-09-25 10:07
@deltaforce I would say this plugin is deprecated in favour of the one mentioned by @atomi

**Comment by deltaforce** [comment] 2017-09-25 11:25
I have tried the one suggested and it is working fine thanks.
